### ISSUE TITLE
Lower than expected coverage of constrained space 

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [AnthonyLloyd/CsCheck#11]
Howdy, I'm observing a somewhat unexpected behavior.

## Problem explanation

I have a test space that is small enough to cover completely, but CsCheck's search strategy doesn't cover the entire space with high probability. 

But I get that it is random, so it is fine that it doesn't some of the time. However, what I found surprising is that it the generator runs a low probability of covering the search space in 1 pass. That is to say that the chance that Sampling N unique int entries from a constrained `IntGen[0, N]` is basically zero (measured at  < 0.001% of trials).

In aggregate the generators will cover 64-65% of the test space in a single pass. (this number is close to 1 stddev of a normal distribution 🤔) . That is to say, the number of distinct samples n after sampling N times follows `n/N ~= 0.64 = 64%`

## Concrete questions

1. Does the random number generator follow a uniform distribution? 
2. Is there a way to influence this?

For my use case I can just use Random directly and shuffle but it would be nice to unify my exhaustive testing into the CsCheck framework for uniformity's sake.

Here is some quick and dirty test code:
https://gist.github.com/AlgorithmsAreCool/31530f7d63fc17461c1d5dd77a35b504

that produces output like this on my machine
```
D:\junk\cscheck-experiments via .NET v7.0.200 🎯 net7.0 took 16s
❯ dotnet run
Hello, World!
Covered the entire search space in (80) 0.00080000% of cases
Covered an average of 65.96893063% cases
```

**Comment by AnthonyLloyd** [comment]
Hi, Yes, you are correct it's not uniform. You can get a uniform distribution with Gen.Int.Uniform.

The default masks a uniform int to random number of bits. I did this after experimenting with the shrinking challenge.
The QuickCheck default is the have a Size that increases and then tries to decrease on shrinking. In our monte carlo way we don't have this but we can pick the distribution and the number of bit is a key limit in our Size measure used for shrinking.

The conclusion I think is better documentation, maybe some other options on the distribution(?) and maybe research on if there is a better default. It's possibly a bit too 'log'y as examples problems tend to be too simple and bigger examples would tend be better tests.

**Comment by AlgorithmsAreCool** [comment]
Hmm a few follow-ups,

1. Is there built in support for constraining the range of a Uniform Int aside from `Where`?
2. What kind of distribution does the default generator follow? Is it Normal? Or it is something spicy?
3. Is it possible to influence the default distribution?

**Comment by AnthonyLloyd** [comment]
1. No it's simple Gen<int>. Actually Gen.Int[start, finish] is uniform.
2. It's a bit weird. You have a random number of bits in the mask (so only 1 in 32 of getting ints in the top half and 1 in 32 it's zero) and then uniform within that mask. There is also Gen.Int.Skew which is parameterised. I think that is a good idea but I've not personally needed it much,
3. No not currently.

**Comment by AlgorithmsAreCool** [comment]
> ...Are you seeing Gen.Int[start, finish] to be non uniform?

Yes, I believe so. Statistics are not my strong suit, but I would assume that on average, sampling a distribution N times would return approximately N unique samples. But i'm only seeing about 0.67 * N uniques.

This is my test code 
```csharp
using CsCheck;

Console.WriteLine("Hello, World!");


TestIntegerSpaceCoverage(10);
TestIntegerSpaceCoverage(100);
TestIntegerSpaceCoverage(1000);
TestIntegerSpaceCoverage(10000);

void TestIntegerSpaceCoverage(int spaceCardinality)
{
    
    Console.WriteLine($"Testing space cardinality of {spaceCardinality:N0}");

    const int iterations = 100_000;

    var intGen = Gen.Int[0, spaceCardinality];

    int perfectCoverageTrialCount = 0;
    int uniquePointCountSum = 0;

    for (int i = 0; i < iterations; i++)
    {
        var uniquePoints = new HashSet<int>();

        intGen.Sample(point => { 
            uniquePoints.Add(point);
        },
            iter: spaceCardinality,
            threads: 1
        );

        //update sum for use in a later average
        uniquePointCountSum += uniquePoints.Count;

        //did we cover 100% of the space?
        if (uniquePoints.Count == spaceCardinality)
            perfectCoverageTrialCount++;
    }


    int totalNumberOfPossiblePoints = iterations * spaceCardinality;
    decimal perfectTrialPercentage = (decimal)perfectCoverageTrialCount / iterations;
    decimal averagePointCoverage = (decimal)uniquePointCountSum / totalNumberOfPossiblePoints;


    Console.WriteLine($"We had {perfectCoverageTrialCount:N0}/{iterations:N0} perfect coverage trials for a overall perfection percentage of {perfectTrialPercentage:P8}");
    
    Console.WriteLine($"In each trial, we covered an average of {averagePointCoverage:P8} of the possible search space");
    //Console.WriteLine($"Across all Trials we covered {overallPointCoverage:P8} of the possible search space");

    Console.WriteLine();
    Console.WriteLine();
}
```

which prints this result on my machine

```
D:\junk\cscheck-experiments via .NET v7.0.200 🎯 net7.0
❯ dotnet run
Hello, World!
Testing space cardinality of 10
We had 152/100,000 perfect coverage trials for a overall perfection percentage of 0.15200000%
In each trial, we covered an average of 67.61360000% of the possible search space


Testing space cardinality of 100
We had 0/100,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.65793000% of the possible search space


Testing space cardinality of 1,000
We had 0/100,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.25770500% of the possible search space


Testing space cardinality of 10,000
We had 0/100,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.21620090% of the possible search space
```

**Comment by AlgorithmsAreCool** [comment]
My previous numbers are slightly wrong due to an off by 1 error. I'm rerunning them...

**Comment by AlgorithmsAreCool** [comment]
Ok, so I have also tested oversampling to ameliorate the issue. I sample N*k times from the distribution and keep the distincts.

k = 1
```
Testing space cardinality of 10
We had 3/10,000 perfect coverage trials for a overall perfection percentage of 0.03000000%
In each trial, we covered an average of 65.03600000% of the possible search space


Testing space cardinality of 100
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.43400000% of the possible search space


Testing space cardinality of 1,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.21708000% of the possible search space


Testing space cardinality of 10,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 63.20771900% of the possible search space
```

k = 2
```
Testing space cardinality of 10
We had 2,179/10,000 perfect coverage trials for a overall perfection percentage of 21.79000000%
In each trial, we covered an average of 87.86600000% of the possible search space


Testing space cardinality of 100
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 86.63760000% of the possible search space


Testing space cardinality of 1,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 86.48026000% of the possible search space


Testing space cardinality of 10,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 86.46837300% of the possible search space
```

k = 4
```
Testing space cardinality of 10
We had 8,641/10,000 perfect coverage trials for a overall perfection percentage of 86.41000000%
In each trial, we covered an average of 98.58600000% of the possible search space


Testing space cardinality of 100
We had 1,524/10,000 perfect coverage trials for a overall perfection percentage of 15.24000000%
In each trial, we covered an average of 98.20060000% of the possible search space


Testing space cardinality of 1,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 98.17487000% of the possible search space


Testing space cardinality of 10,000
We had 0/10,000 perfect coverage trials for a overall perfection percentage of 0.00000000%
In each trial, we covered an average of 98.16757300% of the possible search space
```

k = 8
```
Testing space cardinality of 10
We had 9,978/10,000 perfect coverage trials for a overall perfection percentage of 99.78000000%
In each trial, we covered an average of 99.97800000% of the possible search space


Testing space cardinality of 100
We had 9,692/10,000 perfect coverage trials for a overall perfection percentage of 96.92000000%
In each trial, we covered an average of 99.96870000% of the possible search space


Testing space cardinality of 1,000
We had 7,156/10,000 perfect coverage trials for a overall perfection percentage of 71.56000000%
In each trial, we covered an average of 99.96692000% of the possible search space


Testing space cardinality of 10,000
We had 343/10,000 perfect coverage trials for a overall perfection percentage of 3.43000000%
In each trial, we covered an average of 99.96665500% of the possible search space
```

**Comment by AnthonyLloyd** [comment]
Yes I think you'd be very lucky to get N unique from N sample of uniform(0,N). I think the probability is $\frac{N!}{N^N}$ i.e. numerator is you can any for the first (N), N-1 for the seconds etc hence $N!$ and all any for the denominator hence $N^N$.

**Comment by AlgorithmsAreCool** [comment]
I think.....that maybe I've had too much coffee. I believe your code is working correctly as designed. (of course you already knew that). 

The first warning...
> Yes, I believe so. Statistics are not my strong suit, ...

The second warning...
> I would ASSUME that on average, sampling a distribution N times would return approximately N unique samples....

This assumption is unfounded. There is no guarantee that rolling a die exactly 6 times will get you one of each face of the die. That would be lucky. Therefore, sampling a PRNG N times is NOT expected to commonly produce N unique values. That too would be very lucky.

Based on my useless numerical analysis above, N samples of a uniform distribution produces approximately 0.632 * N unique values due to some effect of cumulative probability that I can't be bothered to figure out right now.

Circling all the way back to my original problem: 
> I have a test space that is small enough to cover completely, but CsCheck's search strategy doesn't cover the entire space with high probability.

This is expected behavior as you have said due to the Monte Carlo style behavior. To deterministically cover all combinations of a space, it is better to just compose some for loops. A fancier alternative might be to walk the space with some type of space filling curve to cover all dimensions in an outward growing manner. 

Either way, nothing to see here, move along.

Thanks for your speedy and patient replies @AnthonyLloyd
