### ISSUE TITLE
[Request] A way to run all tests on the calling thread

### ISSUE THREAD

**Issue by SamPruden** [AnthonyLloyd/CsCheck#12]
I just found this project and I'm having a great experience with it so far, thanks!

However, one snag that I've run into is that I have tests which must be run on the main thread. I was a little surprised that the various testing methods all seem to insist on using the thread pool, regardless of what we do with the `threads` parameter.

I've been able to solve this problem for myself by simply making a copy of the `Sample` method called `SampleUnthreaded` and aggressively ripping out the threading, but it's a little messy to have to do that, and it will be significantly messier if I decide that I need to implement unthreaded versions of the other test methods too.

I'd suggest that passing `threads: 0` to any of the testing methods should run them on the calling thread without touching the pool.

**Comment by AnthonyLloyd** [comment]
Yes it's good idea to run it on the calling thread if threads: 1. I've wanted to factor out the parallel logic. I'll look to do it.
