### ISSUE TITLE
CsCheck 3.0.0 plans

### ISSUE THREAD

**Issue by AnthonyLloyd** [AnthonyLloyd/CsCheck#15]
- [x] Remove SampleOne - can be done with iter: 1, time: -2 to stop the override of setting CsCheck_Time env var.
- [x] Gen.Double overhaul. Multiple types of double mixed by default Integer, Rational, Exponential, EvenlyDistributed.
- [x] More concise display output for double. Automatically working out if it's a fraction and exponential etc.
- [x] Same overhaul and Print for float and decimal.
- [x] Throw for too many iterations in Where clause.
- [x] Rename Cast to Convert? Is it really a Cast?
- [x] Document the size algorithm. Simplfy and optimise any you can.
- [x] Remove SelectTuple
- [x] Remove Gen.Enumerable
- [x] More aggressive passing of min and skipping. Need to make sure no selectors are called.
- [x] Normalise number of func and tuples overloads to 8? AFTER RC1
- [x] ~~Try changing from abstract `Gen<T>` to `IGen<T>` with default implementation.~~
- [x] ~~I think struct Linq can work.~~
- [x] No Wait in faster AFTER RC1
- [x] Look at faster stopping behaviour AFTER RC1
- [x] SigmaSquared combine with Add AFTER RC1
- [x] Test on MathX NSum etc and Weight Order AFTER RC1
- [x] Increase sigma for chi-squared
- [x] Consider adding writeline to sample. Make it the same sig as classify and nice to get the output counts.
- [x] AlphaNumeric length range.
- [x] ~~Stop on first failure?~~
- [x] Add validation. ~~Is there a smarter way of doing this at the Generate?~~
- [x] Add DateOnly and anything else net6.0y.
- [x] More XML docs

I can see the double change already shows up floating point rounding error issues much better.

Planning an rc1 soonish.
Get your breaking change ideas in now please.

**Comment by AnthonyLloyd** [comment]
Anyone if you could try 3.0.0-rc3. I've been through all the repos I can to test it.

**Comment by dadhi** [comment]
@AnthonyLloyd I probably need to check in https://github.com/dadhi/ImTools 
My current CsCheck version is 2.10.1

**Comment by AnthonyLloyd** [comment]
@dadhi I've checked ImTools, all good. The only breaking change is the V0, V1s go to more standard Item1, Item2.

**Comment by AnthonyLloyd** [comment]
3.0.0 has now been released.

**Comment by dadhi** [comment]
@AnthonyLloyd Thanks for the check and congrats on the new version release!
