### ISSUE TITLE
Gen.OneOfConst of empty array

### ISSUE THREAD

**Issue by ploeh** [AnthonyLloyd/CsCheck#17]
Apologies for this rather vague drive-by issue description, but I recently wrote a property that utilised `Gen.OneOfConst` against a generated array. I'm sorry that this isn't a minimal, reproducible example, but hopefully it gives you an idea of what I mean:

```csharp
[Fact]
public void RoomBooked()
{
    (from rooms in GenRoom.ArrayUnique
     from arrival in Gen.Date.Select(DateOnly.FromDateTime)
     from i in Gen.Int[1, 1_000]
     let departure = arrival.AddDays(i)
     from room in Gen.OneOfConst(rooms)
     from id in Gen.Guid
     let booking = new Booking(id, room.Name, arrival, departure)
     select (rooms, booking))
    .Sample((rooms, booking) =>
    {
        var sut = new FakeReadRegistry(rooms);

        sut.RoomBooked(booking);
        var actual = sut.GetFreeRooms(booking.Arrival, booking.Departure);

        Assert.DoesNotContain(booking.RoomName, actual.Select(r => r.Name));
    });
}
````

This property would fail most of the time with an exception like this:

```
  Message: 
    ---- System.DivideByZeroException : Attempted to divide by zero.

  Stack Trace: 
Check.Sample[T](Gen`1 gen, Action`1 assert, String seed, Int64 iter, Int32 time, Int32 threads, Func`2 print)
Check.Sample[T1,T2](Gen`1 gen, Action`2 assert, String seed, Int64 iter, Int32 time, Int32 threads, Func`2 print)
FakeReadRegistryProperties.RoomBooked() line 33
----- Inner Stack Trace -----
PCG.Next(UInt32 maxExclusive)
<>c__DisplayClass54_0`1.<OneOfConst>b__0(PCG pcg, Size min, Size& size)
<>c__DisplayClass41_0`3.<SelectMany>b__0(PCG pcg, Size min, Size& size)
<>c__DisplayClass41_0`3.<SelectMany>b__0(PCG pcg, Size min, Size& size)
<>c__DisplayClass5_0`2.<Select>b__0(PCG pcg, Size min, Size& size)
<>c__DisplayClass5_0`2.<Select>b__0(PCG pcg, Size min, Size& size)
GenCreate`1.Generate(PCG pcg, Size min, Size& size)
<>c__DisplayClass9_0`1.<Sample>g__Worker|0(Object _)
```

Notice the `DivideByZeroException`. It took me some time to figure out that the problem might be that the array passed to `Gen.OneOfConst` might be empty.

The fix on my end was to change the first line to

```csharp
from rooms in GenRoom.ArrayUnique.Nonempty
```

but it took me some time to troubleshoot the issue.

May I suggest that `Gen.OneOfConst` throws a more descriptive exception if passed an empty collection?

Something like

> An empty collection was passed to Gen.OneOfConst, but it's impossible to pick a random value from the empty set. Please supply a collection with at least one element.

This could potentially save some other poor soul some time in the future.

**Comment by AnthonyLloyd** [comment]
Thanks and I can easily reproduce. There is very little validation on the collection sizes and ranges and they always end up with a divide by zero in the RNG.
It's good timing as I'm putting together v3.0.0. I always have an eye on performance especially with SelectMany/bind but you are right there needs to be something more helpful. Added to my v3 list.

**Comment by AnthonyLloyd** [comment]
And you have reminded me that now I'm moving to net6.0 I can add DateOnly etc. Thanks

**Comment by AnthonyLloyd** [comment]
3.0.0 has been reelased now with validation added.
