### ISSUE TITLE
SampleConcurrentAsync?

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [AnthonyLloyd/CsCheck#19]
Do you have any thoughts about the addition of a SampleConcurrentAsync method to the library?

**Comment by AnthonyLloyd** [comment]
Hi, I have recently add support for the operations to be Tasks https://github.com/AnthonyLloyd/CsCheck/commit/fab981f62829a5e3a9748e5ed0c364f3152cf8a1. I'll release that. I'm not sure if there needs to an async SampleConcurrentAsync or if this is enough. I'll have a think. Were you just looking to use async operations?

**Comment by AlgorithmsAreCool** [comment]
I believe these changes are sufficient, i don't need to "await" the entire SampleConcurrent operation. A normal blocking call is adequate

**Comment by AlgorithmsAreCool** [comment]
Hmm, any concern about deadlocking by just calling `Wait()` ?

**Comment by AnthonyLloyd** [comment]
I've released this now with `.GetAwaiter().GetResult()` instead of `Wait()`. They are run in Threads so there is chance of deadlock unless it's a real one in user code.
