### ISSUE TITLE
[Question] I have a random set of items added to my data structure then looked up

### ISSUE THREAD

**Issue by dadhi** [AnthonyLloyd/CsCheck#3]
@AnthonyLloyd Hello,
I am pretty new to the property-based and random testing, so sorry if the question is stupid.

I have my own data structure (immutable tree) with the method `AddOrUpdate<K,V>(this MyTree<K,V> t, int hash, K key, V val)`.

I want generate a random set of int keys (for simplicity) add them to the tree, then afterwards verify the every key is present via lookup `GetValueOrDefault` method.

Ideally, if the problem found I want to get a smallest set possible, so that I can repeat the test manually and debug the issue.

My current approach is seemingly bad and I have a random failure without possibility to debug the problem: https://github.com/dadhi/ImTools/blob/5c323979b3fcdb0381b0d00efb87fd7ccfbc9a2d/test/ImTools.UnitTests/ImHashMap234Tests.cs#L213

**Comment by AnthonyLloyd** [comment]
Hey @dadhi,

Not stupid at all for a few reasons.

First, it's helped show a bug in the total no tests run that I've checked in a fix for now.

Second, it's a good little example of this test using CsCheck (had to set size as it's quite rare):

```csharp
[Fact]
public void AddOrUpdate_random_items_and_randomly_checking_CsCheck()
{
    const int upperBound = 100000;
    Gen.Int[0, upperBound].Array.Sample(ints =>
    {
        var m = ImHashMap234<int, int>.Empty;
        foreach (int n in ints)
        {
            m = m.AddOrUpdate(n, n);
            Assert.Equal(n, m.GetValueOrDefault(n));
        }
        Assert.Equal(0, m.GetValueOrDefault(upperBound + 1));
        Assert.Equal(0, m.GetValueOrDefault(-1));
    }, size: 100_000);
}
``` 

Once I saw it fail I then reduced the size of the array and upperBound to give the shrinking a hand (I've also added the most shrunk seed I've got so far):

```csharp
[Fact]
public void AddOrUpdate_random_items_and_randomly_checking_CsCheck2()
{
    const int upperBound = 91250;
    Gen.Int[0, upperBound].Array[1, 12].Sample(ints =>
    {
        var m = ImHashMap234<int, int>.Empty;
        for (int i = 0; i < ints.Length; i++)
        {
            int n = ints[i];
            m = m.AddOrUpdate(n, n);
            var actual = m.GetValueOrDefault(n);
            if (n != actual)
            {
                if (i + 1 != ints.Length) writeLine($"Not at end i = {i}");
                writeLine($"Array = {string.Join(", ", ints)}");
            }
            Assert.Equal(n, actual);
        }
        Assert.Equal(0, m.GetValueOrDefault(upperBound + 1));
        Assert.Equal(0, m.GetValueOrDefault(-1));
    }, size: 100_000_000, seed: "0ZPySr9kwyWr");
}
```
Array = 85213, 8184, 14819, 38204, 1738, 6752, 38204, 22310, 86961, 33016, 72555, 25102

A very interesting bug that needs length 12 array with quite high values.

Third reason was that John Hughes covered testing a dictionary insert in the following very interesting talk. He has a good way of testing it that I'll have a go at writing too. Key points are what metamorphic testing is and oversizing ints, array size etc can catch bugs much quicker. 

[How to specify it!](https://youtu.be/G0NUOst-53U?t=1639)

**Comment by dadhi** [comment]
@AnthonyLloyd Thanks for test and the explanation! I will try it out Today.

Interesting that I saw the talk mentioned, even couple of times but did not quite get it - I mean the applied knowledge. Likely I did not have a familiar pain-inducing example before my eyes at that moment.

**Comment by dadhi** [comment]
@AnthonyLloyd Thanks to the CsCheck and your example I was able to find and fix issues. Thanks.

Maybe it would be helpful to include into the CsCheck exception output the guide on how to use the "seed",
and/or automate the shrunk array output (at least for the primitive types). Or also include the note on how to get the array out.

**Comment by AnthonyLloyd** [comment]
Cool. I've update the exception message for the seed a bit more. It also now prints the shrunk sample for simple types and have added a print optional parameter to be able to do this yourself more easily. Thanks I think this makes it easier to use.

I've also done written the metamorphic code (and added ArrayUnique for a unique array). It just inserts 2 key/values in opposite order but we know the end result should be the same:

```csharp
static Gen<ImHashMap234<int, int>> GenMap(int upperBound) =>
    Gen.Int[0, upperBound].ArrayUnique.SelectMany(ks =>
        Gen.Int.Array[ks.Length].Select(vs =>
        {
            var m = ImHashMap234<int, int>.Empty;
            for (int i = 0; i < ks.Length; i++)
                m = m.AddOrUpdate(ks[i], vs[i]);
            return m;
        }));


[Fact]
public void AddOrUpdate_random_items_and_randomly_checking_metamorphic()
{
    const int upperBound = 100000;
    Gen.Select(GenMap(upperBound), Gen.Int[0, upperBound], Gen.Int, Gen.Int[0, upperBound], Gen.Int)
    .Sample(t =>
    {
        var (m, k1, v1, k2, v2) = t;
        var m1 = m.AddOrUpdate(k1, v1).AddOrUpdate(k2, v2);
        var m2 = k1 == k2 ? m.AddOrUpdate(k2, v2) : m.AddOrUpdate(k2, v2).AddOrUpdate(k1, v1);
        var s1 = m1.Enumerate().OrderBy(i => i.Key);
        var s2 = m2.Enumerate().OrderBy(i => i.Key);
        Assert.Equal(s1.Select(i => i.Key), s2.Select(i => i.Key));
        Assert.Equal(s1.Select(i => i.Value), s2.Select(i => i.Value));
    }, size: 1_000_000);
}
```

I'll run it on your new code.

**Comment by dadhi** [comment]
@AnthonyLloyd Interesting, will try it out.

**Comment by AnthonyLloyd** [comment]
I'll release these changes in the next couple of days, I have one other to make also.

**Comment by AnthonyLloyd** [comment]
1.1.0 released now with better message and ArrayUnique used above.

I've update the Map code to latest and see failures in the metamorphic test. As the John's talk says this metamorphic tests give very good testing coverage.

**Comment by dadhi** [comment]
Great, I will look and close the issue. I think, I got all my answers. Thank you.

**Comment by AnthonyLloyd** [comment]
Now added this as an example to the readme. Thanks I think it's a good class of test problem.

**Comment by AnthonyLloyd** [comment]
In this case there is a useful model-based approach. As per the talk this is the best but not always possible:

```csharp
[Fact]
public void AddOrUpdate_ModelBased()
{
    const int upperBound = 100000;
    Gen.SelectMany(GenMap(upperBound), m =>
        Gen.Select(Gen.Const(m), Gen.Int[0, upperBound], Gen.Int))
    .Sample(t =>
    {
        var dic1 = new Dictionary<int, int>();
        foreach (var entry in t.V0.Enumerate()) dic1.Add(entry.Key, entry.Value);
        dic1[t.V1] = t.V2;
        var dic2 = new Dictionary<int, int>();
        foreach (var entry in t.V0.AddOrUpdate(t.V1, t.V2).Enumerate())
            dic2.Add(entry.Key, entry.Value);
        Assert.Equal(dic1, dic2);
    }
    , size: 1
    , print: t => t + "\n" + string.Join("\n", t.V0.Enumerate()));
}
```

**Comment by dadhi** [comment]
@AnthonyLloyd Found and fix the problem with the help of the methamorphic test, model-based one is passing as well. Thanks and closing.
