### ISSUE TITLE
Docs for beginners

### ISSUE THREAD

**Issue by slimshader** [AnthonyLloyd/CsCheck#31]
Hey, new to property/random testing and love the concept so far.

The problem is not sure how to start with CsCheck I am especially interested in Model-based testing (if I understand it correctly but no Idea what SetSlim is. 

Any chance of makig the docs but more beginner-firendly?

Btw, I am using CsCheck for Unity projects.

**Comment by AnthonyLloyd** [comment]
Hi, sorry I don't have any current plans for more docs. I just have the README and there are Xml Docs on the API.

**Comment by pppls** [comment]
It's true that some doc elements are a bit curt which may make them more difficult to understand. However you can typically find the actual test in the source code which will give you a bit more context. For example, the SetSlim example you're likely referring to
```
    [Fact]
    public void SetSlim_ModelBased()
    {
        Gen.Int.Array.Select(a => (new SetSlim<int>(a), new HashSet<int>(a)))
        .SampleModelBased(
            Gen.Int.Operation<SetSlim<int>, HashSet<int>>(
                (ss, i) => ss.Add(i),
                (hs, i) => hs.Add(i)
            )
        );
    }
```
can be found in SlimCollectionsTests.cs.

So I would recommend cloning the package and just investigating that way if you don't understand something.
