### ISSUE TITLE
API Documentation and User Guide

### ISSUE THREAD

**Issue by jlink** [AnthonyLloyd/CsCheck#5]
In order to use CsCheck - alongside other similar libraries - in my workshops for Property-based testing I‘d like to have a bit more documentation than what README offers. Maybe it’s out there and I couldn’t find it?

**Comment by AnthonyLloyd** [comment]
Sorry it's pretty much just the readme and examples in the repo (and a 1000 others in the MKL.NET link). I've recently added xml docs in the code for intellisense. I was hoping people would blog a little about it which would also help. I think I may need to create better step through documentation soonish but it won't be straight away.

**Comment by jlink** [comment]
Thanks for the answert.
Maybe you want to leave this issue open and update it as soon as you find the time to add to the current documentation.

**Comment by AnthonyLloyd** [comment]
Yes, will do.

**Comment by AnthonyLloyd** [comment]
I think time to close. I'm aiming to increase the xml intellisense, and continue to work on the readme but anything more on the documentation would need some help.
