### ISSUE TITLE
[draft] [idea] Declarative Models and automatic generator composition 

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [AnthonyLloyd/CsCheck#8]
> NOTE 1 : This is not a fully specified proposal, see Pending Design Work at the end
> NOTE 2 : I'd be happy to work on some/all of the features here 

# Introduction and motivation
Today, when we generate non-trivial model objects, we need to manually compose multiple generators with `Select` and then feed the tupled arguments into our model constructor. This method is very flexible but can lead to a fair amount of boilerplate when building an object graph with lots of properties. It is also a bit tricky to use because the tupleing causes us to lose argument names which can get confusing when combining lots of generators.

## Today's Example
```csharp
public record TestAddress(string StreetName, int StreetNumber);
public record TestPerson(string Name, int Age, TestAddress Address);

var personGen =
    Gen.Select(
        Gen.String, Gen.Int, Gen.String, Gen.Int,
        args => {
           var address = new TestAddress(args.Item1, args.Item2);
           var person = new TestPerson(args.Item4, args.Item1, address); //oops, used Item1 instead of 3 here
           return person
        });

personGen.Sample(person => { ... } );
```

I propose a reflection API that lets us mark up an object to be constructed automatically.

# Hypothetical APIs

## Basic Usage
```csharp
//declare model
public record TestAddress(string StreetName, int StreetNumber);
public record TestPerson(string Name, int Age, TestAddress Address);
...
Gen<TestPerson> personGen = Gen.FromModel<TestPerson>();

personGen.Sample(person => { ... } );
```

## Allowing Customizations to Model Generation
I also propose we include new model annotation attributes to customize the generators:
```csharp
//names are hard, "Sampled*"...."Generated*"..."Random*"...?
public class SampledLongAttribute : Attribute {
    public long Start { get; set; } 
    public long Finish { get; set; }  
}
public class SampledDoubleAttribute : Attribute { 
     public double Start { get; set; } 
     public double Finish { get; set; }  
}
public class SampledStringAttribute : Attribute { 
    public int Start { get; set; } 
    public int Finish { get; set; }  
    public char[] Chars { get; set; } 
}
...

//usage
public record TestAddress(
    [SampledString(Start = 1, Finish = 0)] string StreetName, 
    int StreetNumber
);
```

## Custom Generators for a Type
I also propose an API to allow overriding or customization of generation

### Approach 1 : .NET 7 only static interface 
```csharp
//API shape
public interface ICustomGen<T> {
    public static Gen<T> GetGenerator();
}

//usage
public record PersonName(string Value) : ICustomGen<PersonName>
{
    public static Gen<PersonName> GetGenerator() => Gen.String[1, 10].Select(str => new PersonName(str));
}
```

### Approach 2 : Backwards compatible attribute
```csharp
//API shape
public class CustomGenAttribute : Attribute { ... }

//usage
public record PersonName(string Value)
{
    [CustomGen] //only 1 allowed per class, type expected to be Gen<TSelf>
    public static Gen<PersonName> GetGenerator() => Gen.String[1, 10].Select(str => new PersonName(str));
}
```

## Other Notes
- This approach makes it easy to work with wrapper types like `record PersonName(string Value)` so that we can avoid primitive obsession
- Since the infrastructure is composing the generators, it ensures we are using them correctly so that the input space is traversed uniformly across "dimensions"
- It helps us develop complex models and expand the sophistication of our tests while keeping the code maintainable.
- This would also bring us a step closer to cleaner Unit Test integration similar to FsCheck where a test method can be injected with an automatically constructed model object.
 
## Risks
- This is a big expansion of API surface to maintain and brings new higher level complexity to this library.  

## Pending Design Work
- Fully designed API
- Concrete understanding of how to compose Generators to ensure all properties in the object graph are being exercised
- How should model constraints be handled? In the current design proposal, all variables are sampled independently. Is there a way to support scenarios where a model might be dependent on other models
- How to handle recursive / cyclical object graphs (this would be a great win for usability)
- How to integrate this into #7 (If it is decided that it is tractable and a good fit for this lib). The idea would be that we could convert the provided object graph into a high dimensional space that we could then compute tuple coverage over.
- How to provide integration into Model based testing API. Can we declaratively define model operations also?

**Comment by AnthonyLloyd** [comment]
One thing I'd note is that we can't add to the domain classes normally. CsCheck should only be referenced in test projects (though it is designed to be temp referenced in main projects for debug and regression).

Your example is composable:
```csharp
public record TestAddress(string StreetName, int StreetNumber);
public record TestPerson(string Name, int Age, TestAddress Address);

var addressGen =
    Gen.Select(Gen.String, Gen.Int, (streetName, streetNumber) => new TestAddress(streetName, streetNumber));

var personGen =
    Gen.Select(Gen.String, Gen.Int, addressGen, (name, age, address) => new TestPerson(name, age, address));

personGen.Sample(person => { ... } );
```

Gen is composable and is a monad (has Bind which in C# is SelectMany). I was hoping this makes it very easy to compose gens even if address depended on age say (would need bind/SelectMany).

I imagined like [ModelTests](https://github.com/AnthonyLloyd/CsCheck/blob/master/Tests/ModelTests.cs) gens can be test helper classes similar to how we write Fakes.

I'm not completely against reflection. I've asked for it before in Hedgehog, but I've come to realise that if things are easily composed with full control of range of values then that is better.

Reflection brings some complexity and support overheads so it would need to be a separate cs project at least (can be in this repo). Gen is very publicly extendable by design so this shouldn't be a problem.

**Comment by AlgorithmsAreCool** [comment]
Update : Last week or so has been super busy. But I have been doing some prototyping to explore the concept. I'm not yet convinced that my approach is entirely appropriate. I'll try to produce some examples in favor or against it soon

**Comment by AlgorithmsAreCool** [comment]
Yeah, I rely on the linq syntax these days and it composes very well. There might still be some value in a class oriented syntax for very complex models. But so far it has been better to just write the linq generators.

**Comment by AnthonyLloyd** [comment]
Will close but come back with anything new.
