### ISSUE TITLE
[Question] API Docs

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [AnthonyLloyd/CsCheck#9]
@AnthonyLloyd I'd like to contribute some API documentation, are you open to PRs for adding XML docs to the current public APIs?

Also eventually it might be nice to gather those API docs into a documentation page, I can poke around at that also

**Comment by AnthonyLloyd** [comment]
I did add some but improving them and adding more would be very welcome. The documentation is something that has been raised before and could do with improving. I find it quite hard to write the doucmentation and have mainy produced examples as they have come up.

**Comment by AnthonyLloyd** [comment]
Not planning anything in this area. If someone wants to come up with a plan I'd be interested.
